using System.Collections.Generic;
using UnityEngine;

namespace NightCourier.Vehicle
{
    /// <summary>Runtime registry for drive-in charging bays generated by the world builder.</summary>
    public sealed class EVChargingStation : MonoBehaviour
    {
        private static readonly List<EVChargingStation> stations = new List<EVChargingStation>();
        [SerializeField, Min(1)] private float chargingRadius = 7f;

        public static IReadOnlyList<EVChargingStation> Stations => stations;
        public float ChargingRadius => chargingRadius;

        public void Configure(float radius) => chargingRadius = radius;

        private void OnEnable()
        {
            if (!stations.Contains(this)) stations.Add(this);
        }

        private void OnDisable() => stations.Remove(this);
    }
}
